### ISSUE TITLE
docker tries to pull even if image is available locally

### ISSUE THREAD

**Issue by goern** [vpavlin/atomicapp-run#12]
containerapp.py tries to pull the image in question in anyway, even if the image is locally available

```
[tester@rhel7server-mongodb-developer containerapp]$ sudo containerapp --dry-run install nulecule/mongodb-24-rhel7
Namespace(APP='nulecule/mongodb-24-rhel7', action='install', answers='/home/tester/Source/mongoDB-nulecule/containerapp/answers.conf', dryrun=True, func=<function cli_install at 0x13771b8>, quiet=False, recursive=True, target_path=None, update=False, verbose=False)
2015-04-21 15:43:03,782 - containerapp.install - INFO - App name is nulecule/mongodb-24-rhel7, will be populated to None
Trying to pull repository docker-registry.usersys.redhat.com/nulecule/mongodb-24-rhel7 ... not found
Trying to pull repository docker.io/nulecule/mongodb-24-rhel7 ... not found
FATA[0004] Error: image nulecule/mongodb-24-rhel7:latest not found 
Traceback (most recent call last):
  File "/bin/containerapp", line 9, in <module>
    load_entry_point('containerapp==0.1', 'console_scripts', 'containerapp')()
  File "/usr/lib/python2.7/site-packages/containerapp-0.1-py2.7.egg/containerapp/cli/main.py", line 101, in main
    cli.run()
  File "/usr/lib/python2.7/site-packages/containerapp-0.1-py2.7.egg/containerapp/cli/main.py", line 83, in run
    args.func(args)
  File "/usr/lib/python2.7/site-packages/containerapp-0.1-py2.7.egg/containerapp/cli/main.py", line 18, in cli_install
    install.install()
  File "/usr/lib/python2.7/site-packages/containerapp-0.1-py2.7.egg/containerapp/install.py", line 84, in install
    self.utils.pullApp(self.params.app)
  File "/usr/lib/python2.7/site-packages/containerapp-0.1-py2.7.egg/containerapp/utils.py", line 96, in pullApp
    raise Exception("Couldn't pull %s" % image)
Exception: Couldn't pull nulecule/mongodb-24-rhel7
[tester@rhel7server-mongodb-developer containerapp]$ sudo docker images
REPOSITORY                   TAG                 IMAGE ID            CREATED             VIRTUAL SIZE
nulecule/mongodb-24-rhel7    latest              d90f89ba589a        About an hour ago   451.8 MB
openshift/mongodb-24-rhel7   latest              4eed528d5ae1        3 hours ago         504 MB
rhel7                        7.1-4               10acc31def5d        10 weeks ago        154.1 MB
rhel7                        latest              10acc31def5d        10 weeks ago        154.1 MB
docker.io/kubernetes/pause   latest              6c4579af347b        9 months ago        239.8 kB
[tester@rhel7server-mongodb-developer containerapp]$ sudo docker tag d90f89ba589a docker-registry.usersys.redhat.com/nulecule/mongodb-24-rhel7
[tester@rhel7server-mongodb-developer containerapp]$ sudo docker push d90f89ba589a
FATA[0000] You cannot push a "root" repository. Please rename your repository to <user>/<repo> (ex: <user>/docker.io/d90f89ba589a) 
[tester@rhel7server-mongodb-developer containerapp]$ sudo containerapp --dry-run install nulecule/mongodb-24-rhel7
Namespace(APP='nulecule/mongodb-24-rhel7', action='install', answers='/home/tester/Source/mongoDB-nulecule/containerapp/answers.conf', dryrun=True, func=<function cli_install at 0xc401b8>, quiet=False, recursive=True, target_path=None, update=False, verbose=False)
2015-04-21 15:43:45,366 - containerapp.install - INFO - App name is nulecule/mongodb-24-rhel7, will be populated to None
Trying to pull repository docker-registry.usersys.redhat.com/nulecule/mongodb-24-rhel7 ... not found
Trying to pull repository docker.io/nulecule/mongodb-24-rhel7 ... not found
FATA[0002] Error: image nulecule/mongodb-24-rhel7:latest not found 
Traceback (most recent call last):
  File "/bin/containerapp", line 9, in <module>
    load_entry_point('containerapp==0.1', 'console_scripts', 'containerapp')()
  File "/usr/lib/python2.7/site-packages/containerapp-0.1-py2.7.egg/containerapp/cli/main.py", line 101, in main
    cli.run()
  File "/usr/lib/python2.7/site-packages/containerapp-0.1-py2.7.egg/containerapp/cli/main.py", line 83, in run
    args.func(args)
  File "/usr/lib/python2.7/site-packages/containerapp-0.1-py2.7.egg/containerapp/cli/main.py", line 18, in cli_install
    install.install()
  File "/usr/lib/python2.7/site-packages/containerapp-0.1-py2.7.egg/containerapp/install.py", line 84, in install
    self.utils.pullApp(self.params.app)
  File "/usr/lib/python2.7/site-packages/containerapp-0.1-py2.7.egg/containerapp/utils.py", line 96, in pullApp
    raise Exception("Couldn't pull %s" % image)
Exception: Couldn't pull nulecule/mongodb-24-rhel7
[tester@rhel7server-mongodb-developer containerapp]$ sudo docker push d90f89ba589a
FATA[0000] You cannot push a "root" repository. Please rename your repository to <user>/<repo> (ex: <user>/docker.io/d90f89ba589a) 
[tester@rhel7server-mongodb-developer containerapp]$ sudo docker push docker-registry.usersys.redhat.com/nulecule/mongodb-24-rhel7
The push refers to a repository [docker-registry.usersys.redhat.com/nulecule/mongodb-24-rhel7] (len: 1)
Sending image list
Pushing repository docker-registry.usersys.redhat.com/nulecule/mongodb-24-rhel7 (1 tags)
Image 10acc31def5d already pushed, skipping
9e3ab6f17775: Image successfully pushed 
25c72db89025: Image successfully pushed 
e10cc8504a94: Image successfully pushed 
7b8da24b9444: Image successfully pushed 
91866a38a99b: Image successfully pushed 
36d2a7c3b424: Image successfully pushed 
6d1255a6b23c: Image successfully pushed 
9750fbae5f2e: Image successfully pushed 
56a9345eb35a: Image successfully pushed 
91d63297c20e: Image successfully pushed 
85790c0a5ef4: Image successfully pushed 
08873fb74bc0: Image successfully pushed 
d90f89ba589a: Image successfully pushed 
Pushing tag for rev [d90f89ba589a] on {http://docker-registry.usersys.redhat.com/v1/repositories/nulecule/mongodb-24-rhel7/tags/latest}
[tester@rhel7server-mongodb-developer containerapp]$ sudo containerapp --dry-run install nulecule/mongodb-24-rhel7
[sudo] password for tester: 
Namespace(APP='nulecule/mongodb-24-rhel7', action='install', answers='/home/tester/Source/mongoDB-nulecule/containerapp/answers.conf', dryrun=True, func=<function cli_install at 0x1c8e1b8>, quiet=False, recursive=True, target_path=None, update=False, verbose=False)
2015-04-21 16:23:38,131 - containerapp.install - INFO - App name is nulecule/mongodb-24-rhel7, will be populated to None
Trying to pull repository docker-registry.usersys.redhat.com/nulecule/mongodb-24-rhel7 ...
d90f89ba589a: Download complete 
10acc31def5d: Download complete 
9e3ab6f17775: Download complete 
25c72db89025: Download complete 
e10cc8504a94: Download complete 
7b8da24b9444: Download complete 
91866a38a99b: Download complete 
36d2a7c3b424: Download complete 
6d1255a6b23c: Download complete 
9750fbae5f2e: Download complete 
56a9345eb35a: Download complete 
91d63297c20e: Download complete 
85790c0a5ef4: Download complete 
08873fb74bc0: Download complete 
Status: Image is up to date for docker-registry.usersys.redhat.com/nulecule/mongodb-24-rhel7:latest
e4a17ad77006c53d5f4d053a75f4eedfb792b94f0956aae644c30a381bcb8522
2015-04-21 16:23:41,933 - containerapp.utils - INFO - Using temporary directory /tmp/appent-mongodb-24-rhel73ilo6l
FATA[0000] Error response from daemon: Could not find the file /application-entity in container mongodb-24-rhel7 
mongodb-24-rhel7
Traceback (most recent call last):
  File "/bin/containerapp", line 9, in <module>
    load_entry_point('containerapp==0.1', 'console_scripts', 'containerapp')()
  File "/usr/lib/python2.7/site-packages/containerapp-0.1-py2.7.egg/containerapp/cli/main.py", line 101, in main
    cli.run()
  File "/usr/lib/python2.7/site-packages/containerapp-0.1-py2.7.egg/containerapp/cli/main.py", line 83, in run
    args.func(args)
  File "/usr/lib/python2.7/site-packages/containerapp-0.1-py2.7.egg/containerapp/cli/main.py", line 18, in cli_install
    install.install()
  File "/usr/lib/python2.7/site-packages/containerapp-0.1-py2.7.egg/containerapp/install.py", line 88, in install
    self.params.loadMainfile(mainfile_path)
  File "/usr/lib/python2.7/site-packages/containerapp-0.1-py2.7.egg/containerapp/params.py", line 70, in loadMainfile
    raise Exception("%s not found: %s" % (MAIN_FILE, path))
Exception: nulecule not found: /tmp/appent-mongodb-24-rhel73ilo6l/application-entity/nulecule
[tester@rhel7server-mongodb-developer containerapp]$
```

**Comment by vpavlin** [comment]
Fixed by 12dd1237f34945258577659c8e33da1b52f4b3f2
