### ISSUE TITLE
running container-app.py ootb errors on plugin manager.

### ISSUE THREAD

**Issue by jayunit100** [vpavlin/atomicapp-run#3]
Hi mister pavlin... Finally hacking on an implementation.   But when I ran container-app.py, it complained about the imports.    Is there some special pythonic way of running this that im missing ?   Thanks !
```
[jay@rhbd atomicapp-run]$ ./containerapp.py
Traceback (most recent call last):
  File "./containerapp.py", line 3, in <module>
    import run
  File "/home/jay/Development/PROJECT_Atomicapp/atomicapp-run/run.py", line 14, in <module>
    from yapsy.PluginManager import PluginManager
ImportError: No module named yapsy.PluginManager
```
```

**Comment by vpavlin** [comment]
Fixed with 613835b09c640674cb16a4d09e29820aeed568d6
